# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "986f61ac87647b7614f7474d691497bb"
name = "dsct-77"
handle = "dsct-77"
application_url = "https://venture-pairs-size-educated.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dddxt.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,read_discounts"

[auth]
redirect_urls = [
  "https://venture-pairs-size-educated.trycloudflare.com/auth/callback",
  "https://venture-pairs-size-educated.trycloudflare.com/auth/shopify/callback",
  "https://venture-pairs-size-educated.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
